import type { Metadata } from "next";
import * as f from "@/fonts";
import "../styles/globals.scss";

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_BASEURL as string),
  title: {
    default: "ASPACE Network and Technologies Limited",
    template: `%s | ASPACE`,
  },
  description: "Generated by create next app",
  twitter: {
    title: "FiWears",
    card: "summary_large_image",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${f.poppins.className} ${f.raleway.variable} ${f.workSans.variable} ${f.unica}`}
      >
        {children}
      </body>
    </html>
  );
}
